// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

#[macro_use]
extern crate log;

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
pub(crate) mod device_manager;
/// Resource store for configured microVM resources.
pub mod resources;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::linux::vstate;
#[cfg(target_os = "macos")]
mod macos;
/// M9 VM snapshot file format + (de)serialization (macOS).
#[cfg(target_os = "macos")]
pub mod snapshot;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

use std::fmt::{Display, Formatter};
use std::io;
use std::os::unix::io::AsRawFd;
use std::sync::atomic::{AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

#[cfg(target_arch = "x86_64")]
use crate::device_manager::legacy::PortIODeviceManager;
use crate::device_manager::mmio::MMIODeviceManager;
use crate::vstate::VcpuEvent;
use crate::vstate::{Vcpu, VcpuHandle, VcpuResponse, Vm};
#[cfg(target_os = "macos")]
use hvf::VcpuState;

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
use devices::{BusDevice, DeviceType};
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{self, EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
#[cfg(target_os = "macos")]
use utils::pollable_channel::{PollableChannelReciever, PollableChannelSender};
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Firecracker was shut down after intercepting a restricted system call.
pub const FC_EXIT_CODE_BAD_SYSCALL: u8 = 148;
/// Firecracker was shut down after intercepting `SIGBUS`.
pub const FC_EXIT_CODE_SIGBUS: u8 = 149;
/// Firecracker was shut down after intercepting `SIGSEGV`.
pub const FC_EXIT_CODE_SIGSEGV: u8 = 150;
/// Bad configuration for microvm's resources, when using a single json.
pub const FC_EXIT_CODE_BAD_CONFIGURATION: u8 = 152;
/// Command line arguments parsing error.
pub const FC_EXIT_CODE_ARG_PARSING: u8 = 153;
/// The guest asked to **reboot** (PSCI `SYSTEM_RESET`), as distinct from power-off
/// (`SYSTEM_OFF` → `FC_EXIT_CODE_OK`). libkrun is single-shot, so a reboot still tears the
/// worker process down — this code lets the supervisor tell a reboot apart from a clean
/// power-off and relaunch the worker (limina patch: VMM-as-child reboot). (limina addition.)
pub const FC_EXIT_CODE_REBOOT: u8 = 125;

/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Polly error wrapper.
    EventManager(event_manager::Error),
    /// I8042 Error.
    #[cfg(target_arch = "x86_64")]
    I8042Error(devices::legacy::I8042DeviceError),
    /// Cannot access kernel file.
    KernelFile(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot load command line.
    LoadCommandline(kernel::cmdline::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    /// Write to the serial console failed.
    Serial(io::Error),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Cannot create Timer file descriptor.
    TimerFd(io::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU resume failed.
    VcpuResume,
    /// vCPU pause failed (a vCPU did not report `Paused` in time). Used by the M9 snapshot path.
    VcpuPause,
    /// A snapshot save/restore step failed (GIC blob, or serialization). Used by M9.
    Snapshot,
    /// A snapshot file read/write failed.
    SnapshotIo(std::io::Error),
    /// Cannot spawn a new Vcpu thread.
    VcpuSpawn(std::io::Error),
    /// Vm error.
    Vm(vstate::Error),
    /// Error thrown by observer object on Vmm initialization.
    VmmObserverInit(utils::errno::Error),
    /// Error thrown by observer object on Vmm teardown.
    VmmObserverTeardown(utils::errno::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            EventManager(e) => write!(f, "Event manager error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            I8042Error(e) => write!(f, "I8042 error: {e}"),
            KernelFile(e) => write!(f, "Cannot access kernel file: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            LoadCommandline(e) => write!(f, "Cannot load command line: {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            Serial(e) => write!(f, "Error writing to the serial console: {e:?}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            TimerFd(e) => write!(f, "Error creating timer fd: {e}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuResume => write!(f, "vCPUs resume failed."),
            VcpuPause => write!(f, "vCPUs pause failed."),
            Snapshot => write!(f, "VM snapshot save/restore failed."),
            SnapshotIo(e) => write!(f, "VM snapshot file I/O failed: {e}"),
            VcpuSpawn(e) => write!(f, "Cannot spawn Vcpu thread: {e}"),
            Vm(e) => write!(f, "Vm error: {e}"),
            VmmObserverInit(e) => write!(
                f,
                "Error thrown by observer object on Vmm initialization: {e}"
            ),
            VmmObserverTeardown(e) => {
                write!(f, "Error thrown by observer object on Vmm teardown: {e}")
            }
        }
    }
}

/// Trait for objects that need custom initialization and teardown during the Vmm lifetime.
pub trait VmmEventsObserver {
    /// This function will be called during microVm boot.
    fn on_vmm_boot(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
    /// This function will be called on microVm teardown.
    fn on_vmm_stop(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
pub struct Vmm {
    // Guest VM core resources.
    guest_memory: GuestMemoryMmap,
    pub(crate) arch_memory_info: ArchMemoryInfo,

    kernel_cmdline: KernelCmdline,

    vcpus_handles: Vec<VcpuHandle>,
    exit_evt: EventFd,
    vm: Vm,
    exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    exit_code: Arc<AtomicI32>,

    // Guest VM devices.
    mmio_device_manager: MMIODeviceManager,
    #[cfg(target_arch = "x86_64")]
    pio_device_manager: PortIODeviceManager,

    // Out-of-band live pause/resume requests: the C API sends `VmCtl` from
    // another thread; the event loop freezes or wakes the vCPUs. A single
    // channel rather than one eventfd per operation, so the event loop observes
    // the requests in the order they were made. Device worker threads are
    // notify-driven, so a frozen guest leaves them idle without explicit
    // handling.
    #[cfg(target_os = "macos")]
    vm_ctl_tx: PollableChannelSender<VmCtl>,
    #[cfg(target_os = "macos")]
    vm_ctl_rx: PollableChannelReciever<VmCtl>,
    #[cfg(target_os = "macos")]
    paused: bool,
    #[cfg(target_os = "macos")]
    paused_at: u64,
    /// limina: a handle for pushing runtime display resizes into the live virtio-gpu device,
    /// captured when the GPU device is attached. `None` if no display/GPU is configured.
    #[cfg(feature = "gpu")]
    gpu_resize_handle: Option<devices::virtio::DisplayResizeHandle>,

    /// limina M9.3: the attached virtio-gpu device itself, for GPU snapshot/replay (the venus
    /// re-creation journal round-trip with the GPU worker). `None` if no GPU is configured.
    #[cfg(feature = "gpu")]
    gpu_device: Option<Arc<Mutex<devices::virtio::Gpu>>>,

    /// limina: a handle for pushing balloon targets into the live virtio-balloon device, captured
    /// when the balloon is attached. `None` if no balloon (e.g. the `tee` build).
    balloon_control_handle: Option<devices::virtio::BalloonControlHandle>,

    /// limina (M9 snapshot/suspend): the shared vCPU list, used to kick every vCPU out to the
    /// top of its run loop so it notices a snapshot `Pause`. See [`Self::pause_vcpus`].
    #[cfg(target_os = "macos")]
    vcpu_list: std::sync::Arc<devices::legacy::VcpuList>,
}

/// Out-of-band request to the running VM's event loop.
#[cfg(target_os = "macos")]
#[derive(Debug, Clone)]
pub enum VmCtl {
    Pause,
    Resume,
}

impl Vmm {
    /// limina: the runtime display-resize handle for the live virtio-gpu (if a GPU is
    /// attached). limina-vmm uses it to apply window-resize requests to the guest.
    #[cfg(feature = "gpu")]
    pub fn gpu_resize_handle(&self) -> Option<devices::virtio::DisplayResizeHandle> {
        self.gpu_resize_handle.clone()
    }

    /// limina: record the GPU resize handle at attach time (see [`Self::gpu_resize_handle`]).
    #[cfg(feature = "gpu")]
    pub fn set_gpu_resize_handle(&mut self, handle: devices::virtio::DisplayResizeHandle) {
        self.gpu_resize_handle = Some(handle);
    }

    /// limina M9.3: record the GPU device at attach time, for snapshot/replay.
    #[cfg(feature = "gpu")]
    pub fn set_gpu_device(&mut self, gpu: Arc<Mutex<devices::virtio::Gpu>>) {
        self.gpu_device = Some(gpu);
    }

    /// limina M9.3 restore: stage a v5 GPU re-creation section on the GPU device. The
    /// worker replays it at the guest thaw's re-activation (after the thaw reset, before
    /// any queue command). Returns false only if the VM has no GPU device.
    #[cfg(all(feature = "gpu", target_os = "macos"))]
    pub fn restore_gpu(&self, data: Vec<u8>) -> bool {
        match &self.gpu_device {
            Some(gpu) => {
                gpu.lock().unwrap().restore_gpu(data);
                true
            }
            None => {
                warn!("restore: snapshot has a GPU section but this VM has no GPU device");
                false
            }
        }
    }

    /// limina: the balloon control handle for the live virtio-balloon (if attached). limina-vmm
    /// uses it to drive the dynamic-memory target (M6) and read back `actual`.
    pub fn balloon_control_handle(&self) -> Option<devices::virtio::BalloonControlHandle> {
        self.balloon_control_handle.clone()
    }

    /// limina: record the balloon control handle at attach time (see
    /// [`Self::balloon_control_handle`]).
    pub fn set_balloon_control_handle(&mut self, handle: devices::virtio::BalloonControlHandle) {
        self.balloon_control_handle = Some(handle);
    }

    /// Gets the the specified bus device.
    pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>> {
        self.mmio_device_manager.get_device(device_type, device_id)
    }

    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        let vcpu_count = vcpus.len();

        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpu_count);

        for mut vcpu in vcpus.drain(..) {
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());
            // limina M9.3 floor-spike oracle: flag guest touches into the GPU/fs SHM window (unmapped
            // on a fresh --restore worker). No-op cost in steady state (the window is hv_vm_map'd, so
            // it never traps there); only fires after a GPU-bearing restore.
            #[cfg(target_os = "macos")]
            vcpu.set_shm_start(self.arch_memory_info.shm_start_addr);

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }

        // The vcpus start off in the `Paused` state, let them run.
        self.resume_vcpus()?;

        Ok(())
    }

    /// Sends a resume command to the vcpus.
    #[cfg(target_os = "linux")]
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    #[cfg(target_os = "macos")]
    pub fn resume_vcpus(&mut self) -> Result<()> {
        Ok(())
    }

    /// Resume vCPUs that were parked by [`Self::pause_vcpus`] or [`Self::snapshot_vcpus`] (M9 abort
    /// path), so a failed snapshot can put the guest back into execution instead of leaving it
    /// wedged. Rides [`Vmm::resume`], which advances the vtimer offset by the parked time and
    /// waits for each vCPU's `Resumed` ack.
    ///
    /// This is deliberately **separate** from the no-op [`Self::resume_vcpus`] that `start_vcpus`
    /// calls on every boot: on macOS the vCPUs self-start (via the boot channel / direct run) and are
    /// never `Pause`-parked at boot, so a `Resume` there is swallowed with no reply — waiting for
    /// `Resumed` would hang cold boot. Only call this when the vCPUs are actually parked.
    #[cfg(target_os = "macos")]
    pub fn resume_parked_vcpus(&mut self) -> Result<()> {
        self.resume().map_err(|_| Error::VcpuResume)
    }

    /// Sender for live [`VmCtl`] requests. The event loop runs [`Vmm::pause`] /
    /// [`Vmm::resume`] in response.
    #[cfg(target_os = "macos")]
    pub fn vm_ctl_sender(&self) -> PollableChannelSender<VmCtl> {
        self.vm_ctl_tx.clone()
    }

    /// Freeze every vCPU at an instruction boundary. Reversible via [`Vmm::resume`];
    /// the guest's virtual counter is held so timers don't fire en masse on wake.
    /// Idempotent: pausing an already-paused VM is a no-op.
    #[cfg(target_os = "macos")]
    pub fn pause(&mut self) -> std::result::Result<(), String> {
        use crate::vstate::{VcpuEvent, VcpuResponse};
        if self.paused {
            return Ok(());
        }
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Pause)
                .map_err(|e| format!("vcpu pause event: {e:?}"))?;
            hvf::vcpu_request_exit(h.hvf_id()).map_err(|e| format!("vcpu_request_exit: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Paused) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        self.paused_at = unsafe { hvf::mach_absolute_time() };
        self.paused = true;
        Ok(())
    }

    /// Wake every vCPU previously frozen by [`Vmm::pause`], advancing the vtimer
    /// offset by the time spent paused. Idempotent: resuming a running VM is a
    /// no-op.
    #[cfg(target_os = "macos")]
    pub fn resume(&mut self) -> std::result::Result<(), String> {
        use crate::vstate::{VcpuEvent, VcpuResponse};
        if !self.paused {
            return Ok(());
        }
        let paused_ticks = unsafe { hvf::mach_absolute_time() }.saturating_sub(self.paused_at);
        for h in &self.vcpus_handles {
            h.send_event(VcpuEvent::Resume(paused_ticks))
                .map_err(|e| format!("vcpu resume event: {e:?}"))?;
        }
        for h in &self.vcpus_handles {
            match h.response_receiver().recv() {
                Ok(VcpuResponse::Resumed) => {}
                Ok(other) => return Err(format!("unexpected vcpu response: {other:?}")),
                Err(e) => return Err(format!("vcpu response: {e:?}")),
            }
        }
        self.paused = false;
        Ok(())
    }

    /// Quiesce all vCPUs for a snapshot (M9): park every vCPU at a clean
    /// inter-`hv_vcpu_run` boundary so register/GIC state can be serialized
    /// consistently. Upstream's live-pause machinery ([`Vmm::pause`]) parks at
    /// exactly that boundary (busy vCPUs via `vcpu_request_exit`, WFE-parked
    /// ones via the event channel their wait selects on), so M9 rides it.
    #[cfg(target_os = "macos")]
    pub fn pause_vcpus(&mut self) -> Result<()> {
        self.pause().map_err(|_| Error::VcpuPause)
    }

    /// Snapshot every vCPU's architectural state (M9): hand each a per-vCPU reply channel via a
    /// `Snapshot` event, kick them all to the top of their run loops, and collect the states in
    /// vCPU-index order. Each vCPU saves on its own thread (HVF register affinity) and then
    /// parks, so on return the machine is quiesced exactly as after [`Self::pause_vcpus`] —
    /// ready for the caller to serialize the GIC and guest RAM alongside these states.
    #[cfg(target_os = "macos")]
    pub fn snapshot_vcpus(&mut self) -> Result<Vec<VcpuState>> {
        // Participate in the live-pause bookkeeping: the vCPUs park just like
        // [`Vmm::pause`]'s, so [`Vmm::resume`] (via `resume_parked_vcpus`) must
        // see the VM as paused and advance the vtimers by the parked time.
        self.paused_at = unsafe { hvf::mach_absolute_time() };
        let mut receivers = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            let (tx, rx) = crossbeam_channel::unbounded();
            handle
                .send_event(VcpuEvent::Snapshot(tx))
                .map_err(Error::VcpuEvent)?;
            receivers.push(rx);
        }
        self.vcpu_list.kick_all();
        let mut states = Vec::with_capacity(receivers.len());
        for (i, rx) in receivers.into_iter().enumerate() {
            match rx.recv_timeout(Duration::from_millis(5000)) {
                Ok(state) => states.push(*state),
                // Timeout, or a vCPU dropped its reply channel because its save failed.
                Err(e) => {
                    warn!("snapshot: vCPU {i} did not report its state ({e:?})");
                    return Err(Error::VcpuPause);
                }
            }
        }
        self.paused = true;
        Ok(states)
    }

    /// Take a full host-side VM snapshot (M9): quiesce + capture every vCPU, the VM-wide GIC
    /// blob, and guest RAM (skipping the GPU/fs SHM window), then serialize it all to `path`.
    /// On return the vCPUs are parked; the caller tears the worker down (exit "snapshotted").
    #[cfg(target_os = "macos")]
    /// limina M9.2 quiesce oracle: the virtio-mmio devices whose driver has NOT reset them to `INIT`
    /// (`device_status != 0`), i.e. the devices still holding un-drained queues. Empirically (see
    /// `spikes/m9-freeze-trigger/observe-quiesce-status.sh`) an s2idle-suspended guest drives every
    /// device to `0x0` via its `.suspend` callback, so a non-empty result means the guest has NOT
    /// fully quiesced and the snapshot would capture a mid-flight machine (→ M9.1 wedge on restore).
    /// **virtio-gpu (type 16) is excepted** — it has no s2idle PM ops (stays `DRIVER_OK` with live
    /// queues across suspend), so M9.2 is headless-scoped and the GPU is not a quiesce holdout.
    /// Returns `(virtio type id, device id, device_status)` for each holdout.
    #[cfg(target_os = "macos")]
    pub fn quiesce_holdouts(&self) -> Vec<(u32, String, u32)> {
        const VIRTIO_ID_GPU: u32 = 16;
        self.mmio_device_manager
            .virtio_statuses()
            .into_iter()
            .filter(|(type_id, _, status)| *type_id != VIRTIO_ID_GPU && *status != 0)
            .collect()
    }

    /// True once every virtio-mmio device (except virtio-gpu) has quiesced to `INIT`. See
    /// [`quiesce_holdouts`](Self::quiesce_holdouts).
    #[cfg(target_os = "macos")]
    pub fn is_quiesced(&self) -> bool {
        self.quiesce_holdouts().is_empty()
    }

    pub fn save_snapshot(&mut self, path: &std::path::Path) -> Result<()> {
        // limina M9.2: log every virtio-mmio device's status at snapshot time — the ground truth for
        // the quiesce oracle, and a durable record of what the captured machine's devices looked like.
        for (type_id, id, status) in self.mmio_device_manager.virtio_statuses() {
            info!("snapshot: virtio device type={type_id} id={id} device_status=0x{status:x}");
        }
        let vcpus = self.snapshot_vcpus()?;
        // M9.3: capture each DRIVER_OK device's transport state — for diagnostics (the per-snapshot
        // record of which devices were sticky) and the restore-side layout/feature validation. We do
        // NOT drain the queues: the guest re-negotiates (resets) every virtio device itself on s2idle
        // thaw (`virtio_device_restore`), which discards in-flight ring state and old fences, so there
        // is no "completed used entry with no matching completion IRQ" hazard for a restore to hit —
        // the drain that once guarded that is gone. (A drain also cannot be a general oracle: RX-style
        // queues sit at avail>used at idle with pre-posted buffers and never reach avail==used.)
        //
        // The one thing the drain accidentally provided — quiescing device workers so none writes guest
        // RAM mid-`dump_ram` (torn dump; loudest as net RX from gvproxy on the raw path) — is a separate
        // concern tracked in docs/design/m9-suspend-resume.md (worker-quiesce during the dump). It is
        // narrow on the production s2idle path (the guest froze net/blk/etc. to INIT before we snapshot;
        // only the GPU worker is live) and pre-dates this change.
        let devices = self.mmio_device_manager.capture_transport_states();
        for d in &devices {
            info!(
                "snapshot: capturing transport for virtio type={} @0x{:x} status=0x{:x} {} queue(s)",
                d.type_id,
                d.mmio_base,
                d.device_status,
                d.queues.len()
            );
        }
        // M9.3 venus snapshot-replay: the GPU worker serializes its re-creation state (rutabaga
        // journal + venus wire journals + mapped-blob contents). This runs BEFORE the GIC save
        // and the RAM dump on purpose: the worker first DRAINS in-flight guest fences (the guest
        // froze mid-frame; a fence whose completion misses the snapshot never signals in the
        // restored epoch and its waiter wedges — eyeball 2026-07-19), and those drain-time
        // completions write the used ring (RAM, dumped below) and raise IRQs (GIC, saved below).
        // vCPUs are parked, so no new fences arrive. None = nothing to replay (software-2D or
        // stock guest).
        #[cfg(feature = "gpu")]
        let gpu = self
            .gpu_device
            .as_ref()
            .and_then(|g| g.lock().unwrap().snapshot_gpu());
        #[cfg(not(feature = "gpu"))]
        let gpu: Option<Vec<u8>> = None;
        if let Some(g) = &gpu {
            info!("snapshot: GPU re-creation section is {} bytes", g.len());
        }
        // GIC saved after the fence drain so it carries any line the drain-time completions
        // raised.
        let gic = hvf::save_gic_state().map_err(|_| Error::Snapshot)?;
        let gpio = self
            .mmio_device_manager
            .gpio
            .as_ref()
            .map(|g| g.lock().unwrap().save_state());
        let layout = snapshot::LayoutInfo {
            ram_start: self.arch_memory_info.ram_start_addr,
            ram_last: self.arch_memory_info.ram_last_addr,
            shm_start: self.arch_memory_info.shm_start_addr,
            firmware: self.arch_memory_info.ram_start_addr
                == arch::aarch64::layout::DRAM_MEM_START_EFI,
        };
        let ram = self.dump_ram();
        let snap = snapshot::Snapshot {
            vcpus,
            gic,
            gpio,
            layout,
            devices,
            gpu,
            ram,
        };
        snapshot::write(path, &snap).map_err(Error::SnapshotIo)?;
        info!(
            "snapshot written: {} vCPUs, {}-byte GIC, {} RAM regions -> {}",
            snap.vcpus.len(),
            snap.gic.len(),
            snap.ram.len(),
            path.display()
        );
        Ok(())
    }

    /// M9 restore: apply a saved PL061 register file to the fresh GPIO device before the guest
    /// resumes, so the wake injected on resume demuxes (`GPIOMIS = istate & im`) and the guest's
    /// `pl061_resume` sees the register state it left. No-op if the VM has no GPIO device.
    #[cfg(target_os = "macos")]
    pub fn restore_gpio_state(&self, gpio: &devices::legacy::GpioState) {
        if let Some(g) = &self.mmio_device_manager.gpio {
            g.lock().unwrap().restore_state(gpio);
        }
    }

    /// Copy out the guest RAM regions for a snapshot, skipping everything at or above the SHM
    /// window base (the GPU/fs host-shared regions, which are re-established by the guest on
    /// resume, not carried in the snapshot).
    #[cfg(target_os = "macos")]
    fn dump_ram(&self) -> Vec<snapshot::RamRegion> {
        use vm_memory::{Address, Bytes, GuestMemory, GuestMemoryRegion};
        let shm_start = self.arch_memory_info.shm_start_addr;
        let mut regions = Vec::new();
        for region in self.guest_memory.iter() {
            let gpa = region.start_addr().raw_value();
            if gpa >= shm_start {
                continue; // GPU/fs SHM window — not part of the RAM snapshot
            }
            let len = region.len() as usize;
            let mut data = vec![0u8; len];
            // Read straight out of the mapped region; this is the same memory HVF runs on.
            if let Err(e) = self.guest_memory.read_slice(&mut data, region.start_addr()) {
                error!("snapshot: reading RAM region at 0x{gpa:x} failed: {e:?}; skipping");
                continue;
            }
            regions.push(snapshot::RamRegion { gpa, data });
        }
        regions
    }

    /// Configures the system for boot.
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
        _pvh: bool,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
                _pvh,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the inner `GuestMemoryMmap` object if present, or `None` otherwise.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Injects CTRL+ALT+DEL keystroke combo in the i8042 device.
    #[cfg(target_arch = "x86_64")]
    pub fn send_ctrl_alt_del(&mut self) -> Result<()> {
        self.pio_device_manager
            .i8042
            .lock()
            .expect("i8042 lock was poisoned")
            .trigger_ctrl_alt_del()
            .map_err(Error::I8042Error)
    }

    /// Waits for all vCPUs to exit and terminates the Firecracker process.
    pub fn stop(&mut self, exit_code: i32) {
        info!("Vmm is stopping.");

        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Exit from Firecracker using the provided exit code. Safe because we're terminating
        // the process anyway.
        unsafe {
            libc::_exit(exit_code);
        }
    }

    /// Returns a reference to the inner KVM Vm object.
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        #[cfg(target_os = "macos")]
        if source == self.vm_ctl_rx.as_raw_fd() && event_set == EventSet::IN {
            while let Ok(Some(req)) = self.vm_ctl_rx.try_recv() {
                let res = match req {
                    VmCtl::Pause => self.pause(),
                    VmCtl::Resume => self.resume(),
                };
                if let Err(e) = res {
                    error!("vm {req:?} failed: {e}");
                }
            }
            return;
        }

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            let _ = self.exit_evt.read();
            // Query each vcpu for the exit_code.
            // If the exit_code can't be found on any vcpu, it means that the exit signal
            // has been issued by the i8042 controller in which case we exit with
            // FC_EXIT_CODE_OK.
            //
            // The exit code set up by the guest takes preference over the one reported
            // by either a vcpu or the i8042 controller.
            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);
            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);
            let exit_code = if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
                vmm_exit_code
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
                vcpu_exit_code as i32
            };
            self.stop(exit_code);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        // `vm_ctl_rx` is pushed only on macOS, so `mut` is unused elsewhere.
        #[allow(unused_mut)]
        let mut list = vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )];
        #[cfg(target_os = "macos")]
        list.push(EpollEvent::new(
            EventSet::IN,
            self.vm_ctl_rx.as_raw_fd() as u64,
        ));
        list
    }
}
